### ISSUE TITLE
Unable to launch Configuration

### ISSUE THREAD

**Issue by nalier** [Pretzellent/tradeDispenser-classic#1]
Left click or Right click does not launch trade config, I have launched this no other addons enabled and after deleting WTF and Addons folder but still no luck. Thank you for reviving this addon.

**Comment by Pretzellent** [comment]
Hi Nalier, can you try running /td resetpos and try again.

Let me know how it goes.

**Comment by Pretzellent** [comment]
Hi Nalier, I've just pushed in a potential fix. Can you DL and try it again, let me know how you go.

**Comment by nalier** [comment]
This did work TY =D
