### ISSUE TITLE
Addon keeps throwing errors, 

### ISSUE THREAD

**Issue by FredrikOlofsson** [Pretzellent/tradeDispenser-classic#10]
When I run the addon with no other addons loaded I get this error message, the addon seems great but it throws errors and a few moments later swatter complains about error overflow.

To reproduce the error: 
1. login
2. activate the tradeDispenser by pressing the middle of the three buttons "Activate tradeDispenser"
3. send a message by pressing the first of the three buttons: "Broadcast your trade" 
4. error

_Date: 2020-02-13 15:50:09
ID: 1
Error occured in: Global
Count: 1
Message: ...e\AddOns\tradeDispenser\tradeDispenser_Functions.lua line 26:
   Usage: SendChatMessage(text [,type] [,language] [,targetPlayer])
Debug:
   [C]: SendChatMessage()
   ...e\AddOns\tradeDispenser\tradeDispenser_Functions.lua:26: tradeDispenserMessage()
   ...\AddOns\tradeDispenser\tradeDispenser_SlaveFrame.lua:136: tradeDispenserBroadcastItems()
   [string "*:OnClick"]:11:
      [string "*:OnClick"]:1
Locals:
(*temporary) = nil
(*temporary) = "SAY"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  tradeDispenser, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=68)_

**Comment by Pretzellent** [comment]
Hi there @FredrikOlofsson - This now fixed in v1.14

You can find it here: https://www.wowinterface.com/downloads/info25398-tradeDispenser-classic.html
