### ISSUE TITLE
Only trading 1 stack

### ISSUE THREAD

**Issue by bxyoung** [Pretzellent/tradeDispenser-classic#2]
I am having an issue where it only trades 1 stack even though I have it configured to give 2 stacks. Screenshot below

![image](https://user-images.githubusercontent.com/967989/66788576-12e58100-eeb6-11e9-8c5f-fc01a2b0af77.png)

**Comment by Pretzellent** [comment]
I'll take a look

**Comment by bxyoung** [comment]
![image](https://user-images.githubusercontent.com/967989/66788666-71126400-eeb6-11e9-8cab-c83f9fe0e489.png)

**Comment by bxyoung** [comment]
Verbose log attached. I have 300 water in my bags.

**Comment by Pretzellent** [comment]
Cheers, does this work with 2 different items?

**Comment by bxyoung** [comment]
It does not.

**Comment by Pretzellent** [comment]
Alright no worries, thanks that helps a lot. Will get onto it after work.
