### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by T3rdW** [Pretzellent/tradeDispenser-classic#5]
Message: ...\AddOns\tradeDispenser\tradeDispenser_SlaveFrame.lua:77: attempt to concatenate local 'cID' (a nil value)
Time: Tue Oct 22 19:17:55 2019
Count: 72
Stack: ...\AddOns\tradeDispenser\tradeDispenser_SlaveFrame.lua:77: attempt to concatenate local 'cID' (a nil value)

Locals:

**Comment by Pretzellent** [comment]
Hey there do you have any more information on this? Any repro steps?

**Comment by Pretzellent** [comment]
Closing, looked at code. the only place this can happen is with /td verbose 2 or /td verbose 3 (debug logs)
