### ISSUE TITLE
max trade per player doesnt work

### ISSUE THREAD

**Issue by gende0808** [Pretzellent/tradeDispenser-classic#6]
It seems like players can trade me infinitely without being limited.

**Comment by Pretzellent** [comment]
Will take a look, thanks for the report.

**Comment by Pretzellent** [comment]
Hey @gende0808 - is it possible for the next time you do the trades you can add run the following command before hand `/td verbose 3` and screenshot the debug logs? From what I can see it _seems_ like it should be working correctly.

**Comment by gende0808** [comment]
Could it be guildmembers interfere with this feature? So far I only recall having tried it with guildmembers.

**Comment by Pretzellent** [comment]
It looks like it's working as intended then, guild members are not affected by the limit.

**Comment by gende0808** [comment]
Yeah okay that makes sense. I'd say close the issue then. I would suggest removing that or making it optional because I imagine I'm not the only one with guildmembers who like to spam trades for the hell of it :P.

Really commend you for picking up this project though. Love the addon.

**Comment by rgalan89** [comment]
Hello ! Im using the last release but the addon spams 5 times per second to the traded player asking for the configured price when he accepts trade without matching the price. This is some kind of bug? Intented?
