### ISSUE TITLE
sliders stored as floats?

### ISSUE THREAD

**Issue by gende0808** [Pretzellent/tradeDispenser-classic#7]
There's a few sliders such as the maximum amount of trades allowed but if you try to slide it from 1 to 2 it'll show a bunch of decimals instead of just 1 - 2 - 3 - 4 - 5. Not too familiar with lua myself but it might be stored and displayed as a float?

**Comment by Pretzellent** [comment]
Thanks for the report. Fixing this up now, look for a new version on wowinterface.

**Comment by Pretzellent** [comment]
Closing for now.
