### ISSUE TITLE
Addon spams the configured price to the player 5/10 times per second

### ISSUE THREAD

**Issue by rgalan89** [Pretzellent/tradeDispenser-classic#8]
Hello ! Im using the last release but after configuring the addon , 1 gold for 40 mage waters , when a player opens me trade the addon spams 5 times per second via whisper to the traded player the configured price.
 
Also i think does this when the player tries to accept the trade without matching the desired price .

This is some kind of bug? Intented?

**Comment by Pretzellent** [comment]
Not intended, I have an idea of how to fix this, leave it with me

**Comment by rgalan89** [comment]
Great ! Waiting for it ! Thanks!

**Comment by rgalan89** [comment]
Hello , any update about this issue? Its very annoying to the player being spammed , thanks!

**Comment by Pretzellent** [comment]
Hey Rgalan, sorry I think I have a fix for this, will try to get it working in the next few days. Thanks for your patience

**Comment by dankmem** [comment]
awhile ago i modified the addon for personal use to comment out line 336 in tradedispensor_Functions.lua i dont know anything about wow classic addons or lua but it stopped the spam. im guessing that function tradeDispenserAccept() is being called during game ticks or something causing it to spam people via whisper.

**Comment by Pretzellent** [comment]
Hi there @dankmem & @rgalan89 - this is now fixed in v1.14

Thanks for your patience, you can find it here: https://www.wowinterface.com/downloads/info25398-tradeDispenser-classic.html
